services:
  mysql:
    image: server-mysql-image:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 15896302145.saA
      MYSQL_DATABASE: blog
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./db-init-scripts:/docker-entrypoint-initdb.d/
    networks:
      - app-network

  blog-node:
    image: blog-node-image:latest
    container_name: blog-node-container
    volumes:
      - ./data/assets:/usr/src/app/assets
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 15896302145.saA
      DB_NAME: blog

  template-node:
    image: template-node-image:latest
    container_name: template-node-container
    ports:
      - "3001:3000"
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 15896302145.saA
      DB_NAME: blog

networks:
  app-network:
    driver: bridge
