# 使用官方的 Node.js 镜像作为基础镜像
FROM node:18-alpine

# 设置工作目录
WORKDIR /usr/src/app

# 将 package.json 和 package-lock.json 复制到工作目录
COPY blog/package.json ./
COPY blog/dist/ ./dist

# 安装依赖
RUN npm install --production

# 指定容器启动时要暴露的端口
EXPOSE 3000

# 启动应用
CMD ["npm", "start"]
